name: Auto ChangeLog
description: A GitHub Action that generates changelog and commit it automatically.
author: Wjielai
branding:
  icon: 'clock'
  color: 'blue'
inputs:
  committer_username:
    description: 'Username of that user who will commit'
    required: false
    default: 'github-actions[bot]'
  committer_email:
    description: 'Email Address of that user who will commit'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
runs:
  using: 'docker'
  image: 'Dockerfile'